### ISSUE TITLE
Change from `EReal.log` to `ENNReal.log`

### ISSUE THREAD

**Issue by LorenzoLuccioli** [RemyDegenne/testing-lower-bounds#58]
In the file `ERealLogExp.lean`, should we change the namespace from `EReal` to `ENNReal`? This would allow us to use the dot notation with the `log` and `exp`, just like we do with the real versions of these functions. Is there any downside in doing that?

**Comment by RemyDegenne** [comment]
Writing x.log instead of log x rather hurts readability. I think there was a discussion on that point on zulip some time ago and the consensus was that even if dot notation is technically possible, it should not be used.

Recently the infoview changed to use dot notation a lot so it might be showing some x.log, but it really should rather not.
